import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionContext } from "next-auth/react";
import AuthProvider from './../context/AuthProvider';
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Toaster/>
      </body>
   </AuthProvider>
   </html>
  );
}
